import { useState, type FormEvent } from 'react'
import { Edit3, FolderPlus, Plus, Trash2, X } from 'lucide-react'
import { useStore } from '../../context'
import type { Category, CategoryInput } from '../../types'

const emptyCategory: CategoryInput = { slug: '', label: '', subtitle: '', image: '', sortOrder: 1, isActive: true }

export default function CategoriesManager() {
  const { categories, products, saveCategory, deleteCategory } = useStore()
  const [draft, setDraft] = useState<CategoryInput | null>(null)
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!draft) return; setBusy(true); setMessage(''); try { await saveCategory({ ...draft, slug: draft.slug || draft.label.trim().replace(/\s+/g, '-').toLowerCase() }); setDraft(null); setMessage('تم حفظ التصنيف.') } catch (error) { setMessage(error instanceof Error ? error.message : 'تعذر الحفظ.') } finally { setBusy(false) } }
  const remove = async (category: Category) => { const count = products.filter((p) => p.categoryId === category.id).length; if (count) { setMessage(`لا يمكن حذف التصنيف لأنه مرتبط بـ ${count} منتجات. انقل المنتجات أولاً.`); return } if (!window.confirm(`حذف تصنيف «${category.label}»؟`)) return; try { await deleteCategory(category.id) } catch (error) { setMessage(error instanceof Error ? error.message : 'تعذر الحذف.') } }
  return <div className="admin-page"><div className="admin-page-title"><div><small>تنظيم المتجر</small><h1>التصنيفات</h1><p>نظّم المنتجات لتسهيل التصفح.</p></div><button className="primary-action" onClick={() => setDraft({ ...emptyCategory, sortOrder: categories.length + 1 })}><Plus size={18} /> إضافة تصنيف</button></div>
    {message ? <div className="admin-notice">{message}</div> : null}<section className="category-admin-grid">{categories.map((category) => <article key={category.id}><div className="category-admin-image">{category.image ? <img src={category.image} alt="" /> : <FolderPlus />}<span>{products.filter((p) => p.categoryId === category.id).length} منتجات</span></div><div><small>#{category.slug}</small><h2>{category.label}</h2><p>{category.subtitle}</p><span className={`availability ${category.isActive ? 'active' : ''}`}>{category.isActive ? 'نشط' : 'مخفي'}</span></div><footer><button onClick={() => setDraft({ ...category })}><Edit3 size={16} /> تعديل</button><button className="danger" onClick={() => void remove(category)}><Trash2 size={16} /> حذف</button></footer></article>)}</section>
    {draft ? <div className="admin-modal-backdrop" onMouseDown={() => setDraft(null)}><section className="admin-modal compact" onMouseDown={(e) => e.stopPropagation()}><header><div><h2>{draft.id ? 'تعديل التصنيف' : 'تصنيف جديد'}</h2><p>بيانات التصنيف الظاهرة في المتجر.</p></div><button onClick={() => setDraft(null)}><X /></button></header><form onSubmit={submit}><div className="form-grid"><label>اسم التصنيف<input value={draft.label} onChange={(e) => setDraft({ ...draft, label: e.target.value })} required /></label><label>الرابط المختصر<input dir="ltr" value={draft.slug} onChange={(e) => setDraft({ ...draft, slug: e.target.value })} /></label><label>الوصف القصير<input value={draft.subtitle} onChange={(e) => setDraft({ ...draft, subtitle: e.target.value })} /></label><label>الترتيب<input type="number" min="0" value={draft.sortOrder} onChange={(e) => setDraft({ ...draft, sortOrder: Number(e.target.value) })} /></label></div><label>رابط الصورة<input dir="ltr" value={draft.image} onChange={(e) => setDraft({ ...draft, image: e.target.value })} /></label><div className="check-row"><label><input type="checkbox" checked={draft.isActive} onChange={(e) => setDraft({ ...draft, isActive: e.target.checked })} /> ظاهر في المتجر</label></div><footer><button type="button" className="outline-action" onClick={() => setDraft(null)}>إلغاء</button><button className="primary-action" disabled={busy}>{busy ? 'جارٍ الحفظ…' : 'حفظ التصنيف'}</button></footer></form></section></div> : null}
  </div>
}
