import { useState, type FormEvent } from 'react'
import { Edit3, ImagePlus, Plus, Search, Trash2, X } from 'lucide-react'
import { useStore } from '../../context'
import type { Product, ProductInput } from '../../types'

const emptyProduct: ProductInput = { name: '', slug: '', categoryId: '', price: 0, image: '', colors: ['#d8a8a3'], description: '', stockQuantity: 0, featured: false, isActive: true }

export default function ProductsManager() {
  const { products, categories, saveProduct, deleteProduct, settings } = useStore()
  const [query, setQuery] = useState('')
  const [draft, setDraft] = useState<ProductInput | null>(null)
  const [imageFile, setImageFile] = useState<File>()
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')
  const filtered = products.filter((p) => `${p.name} ${p.categoryLabel}`.toLowerCase().includes(query.toLowerCase()))
  const edit = (product: Product) => setDraft({ id: product.id, name: product.name, slug: product.slug, categoryId: product.categoryId, price: product.price, oldPrice: product.oldPrice, image: product.image, badge: product.badge, colors: product.colors, description: product.description, stockQuantity: product.stockQuantity, featured: product.featured, isActive: product.isActive })
  const submit = async (event: FormEvent) => {
    event.preventDefault(); if (!draft) return; setBusy(true); setMessage('')
    try { await saveProduct({ ...draft, slug: draft.slug || draft.name.trim().replace(/\s+/g, '-').toLowerCase() }, imageFile); setDraft(null); setImageFile(undefined); setMessage('تم حفظ المنتج بنجاح.') } catch (error) { setMessage(error instanceof Error ? error.message : 'تعذر حفظ المنتج.') } finally { setBusy(false) }
  }
  const remove = async (product: Product) => { if (!window.confirm(`حذف «${product.name}» نهائياً؟`)) return; try { await deleteProduct(product.id) } catch (error) { setMessage(error instanceof Error ? error.message : 'تعذر الحذف.') } }
  return <div className="admin-page">
    <div className="admin-page-title"><div><small>الكتالوج</small><h1>إدارة المنتجات</h1><p>{products.length} منتجاً في المتجر</p></div><button className="primary-action" onClick={() => setDraft({ ...emptyProduct, categoryId: categories[0]?.id || '' })}><Plus size={18} /> إضافة منتج</button></div>
    {message ? <div className="admin-notice">{message}</div> : null}
    <div className="admin-toolbar"><div className="admin-search"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ابحث عن منتج…" /></div></div>
    <section className="admin-panel table-panel"><div className="responsive-table"><table><thead><tr><th>المنتج</th><th>التصنيف</th><th>السعر</th><th>المخزون</th><th>الحالة</th><th aria-label="الإجراءات" /></tr></thead><tbody>{filtered.map((product) => <tr key={product.id}><td><div className="product-cell"><img src={product.image} alt="" /><span><strong>{product.name}</strong><small>{product.slug}</small></span></div></td><td>{product.categoryLabel}</td><td><strong>{product.price} {settings.currency}</strong>{product.oldPrice ? <small className="old-price">{product.oldPrice}</small> : null}</td><td>{product.stockQuantity}</td><td><span className={`availability ${product.isActive ? 'active' : ''}`}>{product.isActive ? 'نشط' : 'مخفي'}</span></td><td><div className="row-actions"><button onClick={() => edit(product)} aria-label="تعديل"><Edit3 size={17} /></button><button className="danger" onClick={() => void remove(product)} aria-label="حذف"><Trash2 size={17} /></button></div></td></tr>)}</tbody></table></div>{!filtered.length ? <div className="empty-admin">لا توجد نتائج مطابقة.</div> : null}</section>
    {draft ? <div className="admin-modal-backdrop" onMouseDown={() => setDraft(null)}><section className="admin-modal" onMouseDown={(event) => event.stopPropagation()}><header><div><h2>{draft.id ? 'تعديل المنتج' : 'إضافة منتج جديد'}</h2><p>أدخل تفاصيل الحقيبة ثم احفظها.</p></div><button onClick={() => setDraft(null)}><X /></button></header><form onSubmit={submit}>
      <div className="form-grid"><label>اسم المنتج<input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} required /></label><label>الرابط المختصر<input dir="ltr" value={draft.slug} onChange={(e) => setDraft({ ...draft, slug: e.target.value })} placeholder="product-slug" /></label><label>التصنيف<select value={draft.categoryId} onChange={(e) => setDraft({ ...draft, categoryId: e.target.value })} required><option value="">اختر التصنيف</option>{categories.map((c) => <option value={c.id} key={c.id}>{c.label}</option>)}</select></label><label>شارة اختيارية<input value={draft.badge || ''} onChange={(e) => setDraft({ ...draft, badge: e.target.value })} placeholder="وصل حديثاً" /></label><label>السعر<input type="number" min="0" step="0.01" value={draft.price} onChange={(e) => setDraft({ ...draft, price: Number(e.target.value) })} required /></label><label>السعر قبل الخصم<input type="number" min="0" step="0.01" value={draft.oldPrice || ''} onChange={(e) => setDraft({ ...draft, oldPrice: Number(e.target.value) || undefined })} /></label><label>كمية المخزون<input type="number" min="0" value={draft.stockQuantity} onChange={(e) => setDraft({ ...draft, stockQuantity: Number(e.target.value) })} required /></label><label>الألوان (مفصولة بفاصلة)<input dir="ltr" value={draft.colors.join(', ')} onChange={(e) => setDraft({ ...draft, colors: e.target.value.split(',').map((v) => v.trim()).filter(Boolean) })} /></label></div>
      <label>وصف المنتج<textarea rows={3} value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} /></label><div className="image-input"><ImagePlus /><label>صورة المنتج<input type="file" accept="image/*" onChange={(e) => setImageFile(e.target.files?.[0])} /><span>{imageFile?.name || 'اختر صورة من جهازك'}</span></label><span>أو رابط صورة<input dir="ltr" value={draft.image} onChange={(e) => setDraft({ ...draft, image: e.target.value })} /></span></div><div className="check-row"><label><input type="checkbox" checked={draft.featured} onChange={(e) => setDraft({ ...draft, featured: e.target.checked })} /> منتج مميز</label><label><input type="checkbox" checked={draft.isActive} onChange={(e) => setDraft({ ...draft, isActive: e.target.checked })} /> ظاهر في المتجر</label></div><footer><button type="button" className="outline-action" onClick={() => setDraft(null)}>إلغاء</button><button className="primary-action" disabled={busy}>{busy ? 'جارٍ الحفظ…' : 'حفظ المنتج'}</button></footer>
    </form></section></div> : null}
  </div>
}
