import { useEffect, useState, type FormEvent } from 'react'
import { Save, Store } from 'lucide-react'
import { useStore } from '../../context'
import type { StoreSettings as StoreSettingsType } from '../../types'

export default function StoreSettings() {
  const { settings, saveSettings } = useStore()
  const [draft, setDraft] = useState<StoreSettingsType>(settings)
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')
  useEffect(() => setDraft(settings), [settings])
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setMessage(''); try { await saveSettings(draft); setMessage('تم حفظ إعدادات المتجر.') } catch (error) { setMessage(error instanceof Error ? error.message : 'تعذر حفظ الإعدادات.') } finally { setBusy(false) } }
  const update = <K extends keyof StoreSettingsType>(key: K, value: StoreSettingsType[K]) => setDraft((current) => ({ ...current, [key]: value }))
  return <div className="admin-page"><div className="admin-page-title"><div><small>التخصيص</small><h1>إعدادات المتجر</h1><p>بيانات التواصل والشحن والعروض.</p></div></div>{message ? <div className="admin-notice">{message}</div> : null}<form className="settings-form" onSubmit={submit}><section className="admin-panel"><div className="settings-section-title"><span><Store /></span><div><h2>بيانات المتجر</h2><p>المعلومات الأساسية التي تظهر للعملاء.</p></div></div><div className="form-grid"><label>اسم المتجر<input value={draft.storeName} onChange={(e) => update('storeName', e.target.value)} required /></label><label>البريد الإلكتروني<input type="email" dir="ltr" value={draft.email} onChange={(e) => update('email', e.target.value)} required /></label><label>رقم الهاتف<input dir="ltr" value={draft.phone} onChange={(e) => update('phone', e.target.value)} /></label><label>رقم واتساب<input dir="ltr" value={draft.whatsapp} onChange={(e) => update('whatsapp', e.target.value)} /></label><label>رابط إنستغرام<input dir="ltr" value={draft.instagram} onChange={(e) => update('instagram', e.target.value)} /></label><label>رمز العملة<input value={draft.currency} onChange={(e) => update('currency', e.target.value)} /></label></div></section><section className="admin-panel"><div className="settings-section-title"><div><h2>الشحن والعروض</h2><p>تحكم في تكلفة الشحن وشريط العرض.</p></div></div><div className="form-grid"><label>رسوم الشحن<input type="number" min="0" value={draft.shippingFee} onChange={(e) => update('shippingFee', Number(e.target.value))} /></label><label>حد الشحن المجاني<input type="number" min="0" value={draft.freeShippingThreshold} onChange={(e) => update('freeShippingThreshold', Number(e.target.value))} /></label><label>نص الخصم<input value={draft.bannerDiscount} onChange={(e) => update('bannerDiscount', e.target.value)} /></label><label>عنوان العرض<input value={draft.bannerTitle} onChange={(e) => update('bannerTitle', e.target.value)} /></label></div></section><button className="primary-action save-settings" disabled={busy}><Save size={18} /> {busy ? 'جارٍ الحفظ…' : 'حفظ التغييرات'}</button></form></div>
}
